image: docker:latest

services:
  - docker:dind

build:
  stage: build
  script:
    - docker build --tag dummybot:1.0 .
    
test:
   stage: test
   script:
    - docker run -e TOKEN=$DISCORD_ACCESS_TOKEN --network="host" dummybot:1.0
   interruptible: true
   
deploy:
   stage: deploy
   script: 
    - docker run -e TOKEN=$DISCORD_ACCESS_TOKEN --network="host" dummybot:1.0
   when: manual
