build:
  stage: build
  script:
    - git clone https://gitlab.com/salmonmolon/dummybot.git
    - cd dummybot
    - docker build --tag dummybot:latest .
    
test:
   stage: test
   script:
    - docker run -e TOKEN=$DISCORD_ACCESS_TOKEN --network="host" dummybot:latest
   interruptible: true
   
deploy: 
  stage: deploy
  script: 
    - docker run -d -e TOKEN=$DISCORD_ACCESS_TOKEN --network="host" dummybot:latest
