image: docker:latest

services:
  - docker:dind

build:
  stage: build
  script:
    - docker build --tag dummybot:1.0 .
    
run:
   stage: run
   script:
    - docker run -e TOKEN=$DISCORD_ACCESS_TOKEN dummybot:1.0
